# Perturbed optimizers


[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.sandbox.google.com/github/google-deepmind/optax/blob/main/examples/perturbations.ipynb)

We review in this notebook a universal method to transform any function $f$ mapping a pytree to another pytree to a differentiable approximation $f_\varepsilon$, using pertutbations following the method of [Berthet et al. (2020)](https://arxiv.org/abs/2002.08676).

For a random $Z$ drawn from a distribution with continuous positive distribution $\mu$ and a function $f: X \to Y$, its perturbed approximation defined for any $x \in X$ by

$$f_\varepsilon(x) = \mathbf{E}[f (x + \varepsilon Z )]\, .$$

We illustrate here on some examples, including the case of an optimizer function $y^*$ over $C$ defined for any cost $\theta \in \mathbb{R}^d$ by

$$y^*(\theta) = \mathop{\mathrm{arg\,max}}_{y \in C} \langle y, \theta \rangle\, .$$

In this case, the perturbed optimizer is given by

$$y_\varepsilon^*(\theta) = \mathbf{E}[\mathop{\mathrm{arg\,max}}_{y\in C} \langle y, \theta + \varepsilon Z \rangle]\, .$$

In [1]:
import jax
import jax.numpy as jnp
import operator
from jax import tree_util as jtu

from optax import tree_utils as otu
from optax import perturbations

# Argmax one-hot

We consider an optimizer, such as the following `argmax_one_hot` function. It transforms a real-valued vector into a binary vector with a 1 in the coefficient with largest magnitude and 0 elsewhere. It corresponds to $y^*$ for $C$ being the unit simplex. We run it on an example input `values`.

## One-hot function

In [2]:
def argmax_one_hot(x, axis=-1):
  return jax.nn.one_hot(jnp.argmax(x, axis=axis), x.shape[axis])

In [3]:
values = jnp.array([-0.6, 1.9, -0.2, 1.1, -1.0])

one_hot_vec = argmax_one_hot(values)
print(one_hot_vec)

[0. 1. 0. 0. 0.]


## One-hot with pertubations

Our implementation transforms the `argmax_one_hot` function into a perturbed one that we call `pert_one_hot`. In this case we use Gumbel noise for the perturbation.

In [4]:
N_SAMPLES = 100
SIGMA = 0.5
GUMBEL = perturbations.Gumbel()

rng = jax.random.PRNGKey(1)
pert_one_hot = perturbations.make_perturbed_fun(fun=argmax_one_hot,
                                                num_samples=N_SAMPLES,
                                                sigma=SIGMA,
                                                noise=GUMBEL)

In this particular case, it is equal to the usual [softmax function](https://en.wikipedia.org/wiki/Softmax_function). This is not always true, in general there is no closed form for $y_\varepsilon^*$

In [5]:
rngs = jax.random.split(rng, 2)

rng = rngs[0]

pert_argmax = pert_one_hot(values, rng)
print(f'computation with {N_SAMPLES} samples, sigma = {SIGMA}')
print(f'perturbed argmax = {pert_argmax}')
jax.nn.softmax(values/SIGMA)
soft_max = jax.nn.softmax(values/SIGMA)
print(f'softmax = {soft_max}')
print(f'square norm of softmax = {jnp.linalg.norm(soft_max):.2e}')
print(f'square norm of difference = {jnp.linalg.norm(pert_argmax - soft_max):.2e}')

computation with 100 samples, sigma = 0.5
perturbed argmax = [0.01 0.8  0.02 0.16 0.01]
softmax = [0.00549293 0.8152234  0.01222475 0.16459078 0.00246813]
square norm of softmax = 8.32e-01
square norm of difference = 1.98e-02


## Gradients for one-hot with perturbations

The perturbed optimizer $y_\varepsilon^*$ is differentiable, and its gradient can be computed with stochastic estimation automatically, using `jax.grad`.

We create a scalar loss `loss_simplex` of the perturbed optimizer $y^*_\varepsilon$

$$\ell_\text{simplex}(y_{\text{true}} = y_\varepsilon^*; y_{\text{true}})$$  

For `values` equal to a vector $\theta$, we can compute gradients of

$$\ell(\theta) = \ell_\text{simplex}(y_\varepsilon^*(\theta); y_{\text{true}})$$
with respect to `values`, automatically.

In [6]:
# Example loss function

def loss_simplex(values, rng):
  n = values.shape[0]
  v_true = jnp.arange(n) + 2
  y_true = v_true / jnp.sum(v_true)
  y_pred = pert_one_hot(values, rng)
  return jnp.sum((y_true - y_pred) ** 2)

loss_simplex(values, rngs[1])

Array(0.53180003, dtype=float32)

We can compute the gradient of $\ell$ directly

$$\nabla_\theta \ell(\theta) = \partial_\theta y^*_\varepsilon(\theta) \cdot \nabla_1 \ell_{\text{simplex}}(y^*_\varepsilon(\theta); y_{\text{true}})$$

The computation of the jacobian $\partial_\theta y^*_\varepsilon(\theta)$ is implemented automatically, using an estimation method given by [Berthet et al. (2020)](https://arxiv.org/abs/2002.08676), [Prop. 3.1].

In [7]:
# Gradient of the loss w.r.t input values

gradient = jax.grad(loss_simplex)(values, rngs[1])
print(gradient)

[-0.18402426  0.3660836  -0.0462517  -0.09384193 -0.02169794]


We illustrate the use of this method by running 200 steps of gradient descent on $\theta_t$ so that it minimizes this loss.

In [8]:
# Doing 200 steps of gradient descent on the values to have the desired ranks

steps = 200
values_t = values
eta = 0.5

grad_func = jax.jit(jax.grad(loss_simplex))

for t in range(steps):
  rngs = jax.random.split(rngs[1], 2)
  values_t = values_t - eta * grad_func(values_t, rngs[1])

In [9]:
rngs = jax.random.split(rngs[1], 2)

n = values.shape[0]
v_true = jnp.arange(n) + 2
y_true = v_true / jnp.sum(v_true)

print(f'initial values = {values}')
print(f'initial one-hot = {argmax_one_hot(values)}')
print(f'initial diff. one-hot = {pert_one_hot(values, rngs[0])}')
print()
print(f'values after GD = {values_t}')
print(f'ranks after GD = {argmax_one_hot(values_t)}')
print(f'diff. one-hot after GD = {pert_one_hot(values_t, rngs[1])}')
print(f'target diff. one-hot = {y_true}')

initial values = [-0.6  1.9 -0.2  1.1 -1. ]
initial one-hot = [0. 1. 0. 0. 0.]
initial diff. one-hot = [0.   0.85 0.01 0.14 0.  ]

values after GD = [-0.11319756  0.1024728   0.23011085  0.3087453   0.37857407]
ranks after GD = [0. 0. 0. 0. 1.]
diff. one-hot after GD = [0.09 0.18 0.21 0.19 0.33]
target diff. one-hot = [0.1  0.15 0.2  0.25 0.3 ]


# Differentiable ranking

## Ranking function

We consider an optimizer, such as the following `ranking` function. It transforms a real-valued vector of size $n$ into a vector with coefficients being a permutation of $\{0,\ldots, n-1\}$ corresponding to the order of the coefficients of the original vector. It corresponds to $y^*$ for $C$ being the permutahedron. We run it on an example input `values`.

In [10]:
# Function outputting a vector of ranks

def ranking(values):
  return jnp.argsort(jnp.argsort(values))

In [11]:
# Example on random values

n = 6

rng = jax.random.PRNGKey(0)
values = jax.random.normal(rng, (n,))

print(f'values = {values}')
print(f'ranking = {ranking(values)}')

values = [ 0.18784384 -1.2833426   0.6494181   1.2490594   0.24447003 -0.11744965]
ranking = [2 0 4 5 3 1]


## Ranking with perturbations

As above, our implementation transforms this function into a perturbed one that we call `pert_ranking`. In this case we use Gumbel noise for the perturbation.

In [12]:
N_SAMPLES = 100
SIGMA = 0.2
GUMBEL = perturbations.Gumbel()

pert_ranking = perturbations.make_perturbed_fun(ranking,
                                                num_samples=N_SAMPLES,
                                                sigma=SIGMA,
                                                noise=GUMBEL)

In [13]:
# Expectation of the perturbed ranks on these values

rngs = jax.random.split(rng, 2)

diff_ranks = pert_ranking(values, rngs[0])
print(f'values = {values}')

print(f'diff_ranks = {diff_ranks}')

values = [ 0.18784384 -1.2833426   0.6494181   1.2490594   0.24447003 -0.11744965]
diff_ranks = [2.41 0.   3.92 4.93 2.36 1.38]


## Gradients for ranking with perturbations

As above, the perturbed optimizer $y_\varepsilon^*$ is differentiable, and its gradient can be computed with stochastic estimation automatically, using `jax.grad`.

We showcase this on a loss of $y_\varepsilon(\theta)$ that can be directly differentiated w.r.t. the `values` equal to $\theta$.

In [14]:
# Example loss function

def loss_example(values, rng):
  n = values.shape[0]
  y_true = ranking(jnp.arange(n))
  y_pred = pert_ranking(values, rng)
  return jnp.sum((y_true - y_pred) ** 2)

print(loss_example(values, rngs[1]))

29.7414


In [15]:
# Gradient of the objective w.r.t input values

gradient = jax.grad(loss_example)(values, rngs[1])
print(gradient)

[ 5.145397   4.239827   1.2263288  2.1130772  1.2175393 -3.1376717]


As above, we showcase this example on gradient descent to minimize this loss.

In [16]:
steps = 20
values_t = values
eta = 0.1

grad_func = jax.jit(jax.grad(loss_example))

for t in range(steps):
  rngs = jax.random.split(rngs[1], 2)
  values_t = values_t - eta * grad_func(values_t, rngs[1])

In [17]:
rngs = jax.random.split(rngs[1], 2)

y_true = ranking(jnp.arange(n))

print(f'initial values = {values}')
print(f'initial ranks = {ranking(values)}')
print(f'initial diff. ranks = {pert_ranking(values, rngs[0])}')
print()
print(f'values after GD = {values_t}')
print(f'ranks after GD = {ranking(values_t)}')
print(f'diff. ranks after GD = {pert_ranking(values_t, rngs[1])}')
print(f'target diff. ranks = {y_true}')

initial values = [ 0.18784384 -1.2833426   0.6494181   1.2490594   0.24447003 -0.11744965]
initial ranks = [2 0 4 5 3 1]
initial diff. ranks = [2.3  0.   3.81 4.97 2.55 1.37]

values after GD = [-1.2940687  -0.8644269  -0.17311236  0.39050597  0.69519895  1.135534  ]
ranks after GD = [0 1 2 3 4 5]
diff. ranks after GD = [0.12 0.9  2.07 3.04 4.   4.87]
target diff. ranks = [0 1 2 3 4 5]


# General input / outputs (Pytrees)

This method can be applied to any function taking pytrees as input and output in the forward mode, and can also be used to compute derivatives, as illustrated below

In [18]:
tree_a = (jnp.array((0.1, 0.4, 0.5)),
          {'k1': jnp.array((0.1, 0.2)),
           'k2': jnp.array((0.1, 0.1))},
          jnp.array((0.4, 0.3, 0.2, 0.1)))

## Tree argmax

This piecewise constant function applies the argmax to every leaf array of the pytree

In [19]:
argmax_tree = lambda x: jtu.tree_map(argmax_one_hot, x)

In [20]:
argmax_tree(tree_a)

(Array([0., 0., 1.], dtype=float32),
 {'k1': Array([0., 1.], dtype=float32), 'k2': Array([1., 0.], dtype=float32)},
 Array([1., 0., 0., 0.], dtype=float32))

The perturbed approximation applies a perturbed softmax

In [21]:
N_SAMPLES = 100
sigma = 1.0

pert_argmax_fun = perturbations.make_perturbed_fun(argmax_tree,
                                                   num_samples=N_SAMPLES,
                                                   sigma=SIGMA)

In [22]:
pert_argmax_fun(tree_a, rng)

(Array([0.08, 0.34, 0.58], dtype=float32),
 {'k1': Array([0.31, 0.69], dtype=float32),
  'k2': Array([0.51, 0.49], dtype=float32)},
 Array([0.38, 0.3 , 0.2 , 0.12], dtype=float32))

## Scalar loss

In [23]:
def pert_loss(inputs, rng):
  pert_softmax = pert_argmax_fun(inputs, rng)
  argmax = argmax_tree(inputs)
  diffs = jtu.tree_map(lambda x, y: jnp.sum((x - y) ** 2 / 4), argmax, pert_softmax)
  return jtu.tree_reduce(operator.add, diffs)

In [24]:
init_loss = pert_loss(tree_a, rng)

print(f'initial loss value = {init_loss:.3f}')

initial loss value = 0.375


## Gradient computation

The gradient of the scalar loss can be evaluated

In [25]:
grad = jax.grad(pert_loss)(tree_a, rng)

print('Gradient of the scalar loss')
print()
grad

Gradient of the scalar loss



(Array([-0.01304852,  0.06675826, -0.04797449], dtype=float32),
 {'k1': Array([ 0.02245465, -0.08815713], dtype=float32),
  'k2': Array([-0.08147696,  0.2535689 ], dtype=float32)},
 Array([-0.07846132,  0.14177498, -0.06175202,  0.08064784], dtype=float32))

A small step in the gradient direction reduces the value

In [26]:
eta = 1e-1

loss_step = pert_loss(otu.tree_add_scale(tree_a, -eta, grad), rng)

print(f'initial loss value = {init_loss:.3f}')
print(f'loss after gradient step = {loss_step:.3f}')

initial loss value = 0.375
loss after gradient step = 0.333
